### ISSUE TITLE
Namespace and type output in standard view

### ISSUE THREAD

**Issue by milosmalic** [dss-web/23-video-episerver#1]
Using the controller and standard view as in example, I am getting namespace and type output as string, plus iframe with video. So for @Html.Raw(Model.VideoUrl) I am getting

Castle.Proxies.VideoProxy EPiCode.TwentyThreeVideo.Models.Video

iframe src="http://kampanjetv.23video.com/v.ihtml?token=57a215534cc42a5e8f288ba618e963e9&photo%5fid=13238198" width="320" height="568" frameborder="0" border="0" scrolling="no"></iframe

**Comment by milosmalic** [comment]
This is nofix

The error was typo in referencing model type with caps M

**Comment by soderlind** [comment]
goodie :)
