### ISSUE TITLE
23 video integration job failed in Episerver : “Could not create SSL/TLS secure channel” 

### ISSUE THREAD

**Issue by Yogesh2291** [dss-web/23-video-episerver#8]
Client is Alfalaval . I have enabled TLS 1.2 protocol on local client machine but still not getting response from 23API . As we are getting error “Could not create SSL/TLS secure channel” from 23video library DotnetOpenAuth.

**Comment by tomahg** [comment]
Did you solve this?

**Comment by Yogesh2291** [comment]
Yes  I managed to fix the TLS/SSL issue but we are not able to deploy EpiCode.23video dll to any other environment as it does not contain any public key token value.

Please help us to solve this issue.

Please let me know if you need any other information.

Thanks
Yogesh Kumar
